name: Run tests
on: [push]

jobs:
  test-jsonschema:
    name: Run jsonschema tests against this library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: download
        shell: bash
        run: |
          set -e
          py=python3

          $py -m pip install -e .
          $py -m pip install pyperf pytest pytest-subtests

          wget -O jsonschema.tar.gz  https://github.com/python-jsonschema/jsonschema/archive/refs/tags/v4.24.0.tar.gz
          wget -O referencing.tar.gz https://github.com/python-jsonschema/referencing/archive/refs/tags/v0.36.2.tar.gz
          wget -O referencing-suite.tar.gz https://github.com/python-jsonschema/referencing-suite/archive/ee66bf604dc74e79c2ca395873f24ea58e2eca74.tar.gz
          mkdir js rf
          tar --strip-components=1 -C js       -xf jsonschema.tar.gz
          tar --strip-components=1 -C rf       -xf referencing.tar.gz
          tar --strip-components=1 -C rf/suite -xf referencing-suite.tar.gz

          sed -i -e 's/^dynamic =.*/version = "4.24.0"/' js/pyproject.toml
          sed -i -e 's/^dynamic =.*/version = "0.36.2"/' rf/pyproject.toml

          pushd extra/fake_rpds
          $py -m pip install .
          popd

          pushd rf
          $py -m pip install --break-system-packages -e .
          $py -m pytest referencing/tests/
          popd

          pushd js
          $py -m pip install --break-system-packages -e .
          $py -m pytest jsonschema/tests/
          popd
